name: "build & test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: read
        checks: write
        pull-requests: write
        id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # - name: Build all projcets with Gradle Wrapper
    #   working-directory: ./frontier
    #   run: ./gradlew build

    - name: Run Test
      working-directory: ./frontier
      run: ./gradlew :test:test

    # - name: Publish Test Report
    #   uses: mikepenz/action-junit-report@v5
    #   if: success() || failure() # always run even if the previous step fails
    #   with:
    #     include_passed: true
    #     report_paths: '**/build/test-results/test/TEST-*.xml'
    #
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          frontier/test/build/test-results/test/TEST-*.xml
